var path="http://domain.com/googlemap.html",defX="14.57836",defY="121.05769",defZ="14",defImg="";
CKEDITOR.dialog.add("locationmapDialog",function(b){return{title:"Location Map Properties",minWidth:800,minHeight:600,contents:[{id:"mapPointing",label:"Map Pointing",elements:[{type:"hbox",widths:["50%","50%"],children:[{className:"latitude",id:"latitude",label:"* Latitude",type:"text",validate:CKEDITOR.dialog.validate.notEmpty("Latitude field cannot be empty"),onKeyUp:function(a){latitude=a.sender.$.value;longtitude=document.getElementsByClassName("longtitude")[0].getElementsByTagName("input")[0].value;
zoom=document.getElementsByClassName("zoom")[0].getElementsByTagName("input")[0].value;img=document.getElementsByClassName("image")[0].getElementsByTagName("input")[0].value;document.getElementById("map").contentWindow.setinitialize(latitude,longtitude,zoom,img)},setup:function(a){url=decodeURIComponent(a.$.attributes["data-cke-realelement"].nodeValue);el=document.createElement("div");el.innerHTML=url;url=el.getElementsByTagName("iframe")[0].getAttribute("src");url=url.substring(url.lastIndexOf("?")+
1);url=url.split("&");map_x=url[0].split("=");this.setValue(map_x[1])}},{className:"longtitude",id:"longtitude",label:"* Longtitude",type:"text",validate:CKEDITOR.dialog.validate.notEmpty("Longtitude field cannot be empty"),onKeyUp:function(a){latitude=document.getElementsByClassName("latitude")[0].getElementsByTagName("input")[0].value;longtitude=a.sender.$.value;zoom=document.getElementsByClassName("zoom")[0].getElementsByTagName("input")[0].value;img=document.getElementsByClassName("image")[0].getElementsByTagName("input")[0].value;
document.getElementById("map").contentWindow.setinitialize(latitude,longtitude,zoom,img)},setup:function(a){url=decodeURIComponent(a.$.attributes["data-cke-realelement"].nodeValue);el=document.createElement("div");el.innerHTML=url;url=el.getElementsByTagName("iframe")[0].getAttribute("src");url=url.substring(url.lastIndexOf("?")+1);url=url.split("&");map_y=url[1].split("=");this.setValue(map_y[1])},commit:function(){}}]},{type:"hbox",widths:["50%","50%"],children:[{className:"zoom",id:"zoom",label:"* Zoom",
type:"text",validate:CKEDITOR.dialog.validate.notEmpty("Zoom field cannot be empty"),onKeyUp:function(a){latitude=document.getElementsByClassName("latitude")[0].getElementsByTagName("input")[0].value;longtitude=document.getElementsByClassName("longtitude")[0].getElementsByTagName("input")[0].value;zoom=a.sender.$.value;img=document.getElementsByClassName("image")[0].getElementsByTagName("input")[0].value;document.getElementById("map").contentWindow.setinitialize(latitude,longtitude,zoom,img)},setup:function(a){url=
decodeURIComponent(a.$.attributes["data-cke-realelement"].nodeValue);el=document.createElement("div");el.innerHTML=url;url=el.getElementsByTagName("iframe")[0].getAttribute("src");url=url.substring(url.lastIndexOf("?")+1);url=url.split("&");map_z=url[2].split("=");this.setValue(map_z[1])},commit:function(){}},{type:"hbox",widths:["75%","25%"],children:[{className:"image",id:"image",label:"Image",type:"text",onLoad:function(){this.getInputElement().setAttribute("readOnly",!0)},setup:function(a){url=
decodeURIComponent(a.$.attributes["data-cke-realelement"].nodeValue);el=document.createElement("div");el.innerHTML=url;url=el.getElementsByTagName("iframe")[0].getAttribute("src");url=url.substring(url.lastIndexOf("?")+1);url=url.split("&");img=url[3].split("=");this.setValue(img[1])},commit:function(){}},{className:"browse",id:"browse",label:"Browse Server",style:"margin-top:1.35em",type:"button",onClick:function(){var a=new CKFinder;a.callback=function(a){a.hideTool("f0");a.hideTool("f2")};console.log(a);
a.selectActionFunction=function(a){latitude=document.getElementsByClassName("latitude")[0].getElementsByTagName("input")[0].value;longtitude=document.getElementsByClassName("longtitude")[0].getElementsByTagName("input")[0].value;zoom=document.getElementsByClassName("zoom")[0].getElementsByTagName("input")[0].value;img=a?'<img src="'+a+'" />':"";document.getElementsByClassName("image")[0].getElementsByTagName("input")[0].value=a;document.getElementById("map").contentWindow.setinitialize(latitude,longtitude,
zoom,img)};a.popup()}}]}]},{type:"hbox",widths:["50%","50%"],children:[{id:"width",label:"* Width",type:"text",validate:CKEDITOR.dialog.validate.notEmpty("Width field cannot be empty"),setup:function(a){this.setValue(a.$.style.width)},commit:function(){}},{id:"height",label:"* Height",type:"text",validate:CKEDITOR.dialog.validate.notEmpty("Height field cannot be empty"),setup:function(a){this.setValue(a.$.style.height)},commit:function(){}}]},{type:"html",html:'<iframe src="'+CKEDITOR.basePath+"plugins/locationmap/googlemap.html?x="+
defX+"&y="+defY+"&z="+defZ+"&img="+defImg+'" frameborder="0" id="map" style="width:100%; height:400px; margin:auto;"></iframe>',onLoad:function(){(element=b.getSelection().getStartElement())&&(element=element.getAscendant("img",!0));element?(url=decodeURIComponent(element.$.attributes["data-cke-realelement"].nodeValue),el=document.createElement("div"),el.innerHTML=url,url=el.getElementsByTagName("iframe")[0].getAttribute("src"),url=url.substring(url.lastIndexOf("?")+1),queryString=url.split("&"),
x=queryString[0].split("="),map_x=x[1],y=queryString[1].split("="),map_y=y[1],z=queryString[2].split("="),map_z=z[1],void 0!=queryString[3]?(img=queryString[3].split("="),img=img[1]):img="Click and then move the icon to your store location"):url="";!element||"img"!=element.getName()||-1==parseInt(url.search("googlemap"))?(element=b.document.createElement("iframe"),insertMode=!0):insertMode=!1;insertMode||document.getElementById("map").setAttribute("src",CKEDITOR.basePath+"plugins/locationmap/googlemap.html?x="+
map_x+"&y="+map_y+"&z="+map_z+"&img="+img)}}]}],onShow:function(){(element=b.getSelection().getStartElement())&&(element=element.getAscendant("img",!0));element?(url=decodeURIComponent(element.$.attributes["data-cke-realelement"].nodeValue),el=document.createElement("div"),el.innerHTML=url,url=el.getElementsByTagName("iframe")[0].getAttribute("src"),url=url.substring(url.lastIndexOf("?")+1)):url="";!element||"img"!=element.getName()||-1==parseInt(url.search("googlemap"))?(element=b.document.createElement("iframe"),
this.insertMode=!0):this.insertMode=!1;this.element=element;this.insertMode||this.setupContent(this.element)},onOk:function(){this.commitContent(this.element);var a=b.document.createElement("iframe");src=path+"googlemap.html?x="+this.getValueOf("mapPointing","latitude")+"&y="+this.getValueOf("mapPointing","longtitude")+"&z="+this.getValueOf("mapPointing","zoom")+"&img="+this.getValueOf("mapPointing","image")+"&googlemap=true";a.setAttribute("src",src);a.setAttribute("width",this.getValueOf("mapPointing",
"width"));a.setAttribute("height",this.getValueOf("mapPointing","height"));b.insertElement(a)}}});