<?php
/**
 * @file
 * Adds link & permissions for clearing Drupal cache.
 * Adds a drush command
 */

/**
 * Implements hook_permission().
 * Adds option to add user permissions 
 */
function clear_cache_permission() {
  return array(
    'use clear cache' => array(
      'title' => t('Can clear cache'),
    ),
  );
}

/**
 * Implements hook_menu().
 * Add the clear_cache menu link text, and link it to the clear_cache_truncate() function
 */
function clear_cache_menu() {
  $items = array();
  $items['admin/clearcache'] = array(
    'title' => 'Clear Cache',
    'page callback' => 'clear_cache_truncate',
    'access arguments' => array('use clear cache'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 16,
  );
  return $items;
}
module_load_include('inc', 'clear_cache', 'clear_cache.clear');

/**
 * Implements hook_help().
 * added on drush function
 */
function clear_cache_help($path, $arg) {
  switch ($path) {
    case 'admin/help#clear_cache':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Clear Cache module clears All Drupal Cache by flushing cached data from your database. See the <a href="https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_flush_all_caches/7" target="_blank">drupal_flush_all_cache</a> function on <a href="https://drupal.org/">drupal.org</a>.') . '</p>';
	  $output .= '<h3>' . t('Drush Commands') . '</h3>';
	  $output .= '<dl>';
	  $output .= '<dt>' . t('Examples:') . '</dt>';
	  $output .= '<dd>' . t('<em><div style="background-color: #f7f7f7;border: none;border-radius: 0.25em;color: #308217;margin-bottom: .5em;padding;font-family: Monaco,Consolas,monospace;white-space: pre-wrap;">drush batman-clear-cache</div></em>') . '</dd>';
	  $output .= '<dt>' . t('Alias:') . '</dt>';
	  $output .= '<dd>' . t('<em><div style="background-color: #f7f7f7;border: none;border-radius: 0.25em;color: #308217;margin-bottom: .5em;padding;font-family: Monaco,Consolas,monospace;white-space: pre-wrap;">drush batman</div></em>') . '</dd>';
	  $output .= '<dd>' . t(' Use "<em>drush cache-clear drush</em>" if you dont see the "batman" command under your list of drush commands.') . '</dd>';
	  $output .= '</dl>';
      $output .= '<h3>' . t('Permissions') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('User roles') . '</dt>';
      $output .= '<dd>' . t('The Clear Cache module allows users with the appropriate <a href="@permissions">permissions</a> to clear cache. You can access this via the <a href="@people">People administration page</a>, where you can see your people lists and their roles. If allowed, the user will see the "clear cache" link on the top menu', array('@permissions' => url('admin/people/permissions'), '@people' => url('admin/people'))) . '</dd>';
      $output .= '<dt>' . t('Warning') . '</dt>';
      $output .= '<dd>' . t('<em>Never</em> give the "Clear Cache" permissions to anonymous users or none administrative roles.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
